### ISSUE TITLE
[Art] - CBK Menu

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#12]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

Cryptoblades Kingdoms

### Describe the request and its requirements

![image](https://user-images.githubusercontent.com/25240940/176175226-8a09d70a-3429-4f82-b22f-6344cfd18dbf.png)

Icons for the following:
- Siege
- Guild
- Market

- Village
- Mail
- Land Selection
- Moderation
- Options
- Admin

### Is your art request related to an existing issue? Please describe.

No

### Is there anything stopping this feature from being completed?

No

### Potential Deadline

CBK Beta

### Describe alternatives you've considered

NA

### Banner / Sprite assets

File format: SVG
Aspect ratio: 1x1? not sure on this please choose what is the best

**Comment by seiyria** [comment]
@jeffyzxc make sure to update the titles when you submit these requests

**Comment by jeffyzxc** [comment]
> @jeffyzxc make sure to update the titles when you submit these requests

Sorry about that
