### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Burger menu icon

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#20]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

Cryptoblades Kingdoms

### Describe the request and its requirements

![image](https://user-images.githubusercontent.com/25240940/176671380-7cbc67b5-a888-4638-97c1-f23c544a4ba6.png)

Burger menu icon

### Is your art request related to an existing issue? Please describe.

No

### Is there anything stopping this feature from being completed?

No

### Potential Deadline

CBK Beta

### Describe alternatives you've considered

No alternate

### Banner / Sprite assets

size: 40x40

**Comment by mrlamzz** [comment]
You can download from the General Asset page: https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0f6ff497-8e4a-4009-9ff5-02c45bff0564/
