### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Attack/Command menu icons

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#21]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

Cryptoblades Kingdoms

### Describe the request and its requirements

![image](https://user-images.githubusercontent.com/25240940/176675886-9c15d854-3f80-480c-ac19-c7fa551c692c.png)

Icons for these please. thank you

format: 40x40

### Is your art request related to an existing issue? Please describe.

No

### Is there anything stopping this feature from being completed?

No

### Potential Deadline

CBK Beta

### Describe alternatives you've considered

No alternatives.

### Banner / Sprite assets

size: 40x40
file format: svg

**Comment by mrlamzz** [comment]
The icons are exportable from the design.

You can also download the icons here: https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0f6ff497-8e4a-4009-9ff5-02c45bff0564/

**Comment by jeffyzxc** [comment]
@mrlamzz Hey Zhang couldn't find it in the XD page

**Comment by mrlamzz** [comment]
![image](https://user-images.githubusercontent.com/14541634/180067227-b26cc7e9-28ef-480b-a183-119efe30718d.png)
