### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Gold to king and vice versa

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#22]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

Cryptoblades Kingdoms

### Describe the request and its requirements

a UI for Gold to king exchange and King to gold exchange

- 1 King = 1 gold
- 1  Gold = 0.95 King

currently, we have this spot-on design:
![image](https://user-images.githubusercontent.com/25240940/176856533-3d14f170-bd83-4c43-b099-106e5d2a678a.png)

![image](https://user-images.githubusercontent.com/25240940/176856629-4fce0352-9aee-412a-88e5-75b769af6fd0.png)

### Is your art request related to an existing issue? Please describe.

Nope

### Is there anything stopping this feature from being completed?

Nope

### Potential Deadline

CBK Beta

### Describe alternatives you've considered

No alternatives

### Banner / Sprite assets

NA

**Comment by mrlamzz** [comment]
**Design:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/557efd09-50d6-499b-8a35-00988685ce43/

**Note:**
- User can click the icon in the middle to switch conversion.

**Comment by jeffyzxc** [comment]
> **Design:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/557efd09-50d6-499b-8a35-00988685ce43/
> 
> **Note:**
> 
> * User can click the icon in the middle to switch conversion.

Coolio
