### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Resources image 80x80

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#25]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

Cryptoblades Kingdoms

### Describe the request and its requirements

![image](https://user-images.githubusercontent.com/25240940/177941531-d1321f90-1e8d-47ad-a5bf-b6f46b4fc7d9.png)

resources image for clay, stone, wood with ff format:
- aspect ratio: 1x1
- size: 80x80

### Is your art request related to an existing issue? Please describe.

Nope

### Is there anything stopping this feature from being completed?

Nope

### Potential Deadline

CBK beta

### Describe alternatives you've considered

NA

### Banner / Sprite assets

aspect ratio: 1x1
size: 80x80

**Comment by mrlamzz** [comment]
**You can download it in the General Asset page:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0f6ff497-8e4a-4009-9ff5-02c45bff0564/
