### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Desc and Asc Icon

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#26]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

Cryptoblades Kingdoms

### Describe the request and its requirements

![image](https://user-images.githubusercontent.com/25240940/178009213-77bf3f7f-e3dc-4af1-b01c-9c797beec952.png)

Desc and Asc Icon

### Is your art request related to an existing issue? Please describe.

NA

### Is there anything stopping this feature from being completed?

NA

### Potential Deadline

NA

### Describe alternatives you've considered

NA

### Banner / Sprite assets

size: 40x40

**Comment by mrlamzz** [comment]
**You can download it here:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0f6ff497-8e4a-4009-9ff5-02c45bff0564/

**Comment by jeffyzxc** [comment]
![image](https://user-images.githubusercontent.com/25240940/178472776-33696c8d-9b7a-471c-86ed-92cfd0a795e3.png)

Descending is kinda broken, the line pointing down ain't showing
