### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Guild logo

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#3]
A complete assets/art for guild logo

**Comment by mrlamzz** [comment]
Guild Sigils can be downloaded here: https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0f6ff497-8e4a-4009-9ff5-02c45bff0564/

**Comment by jeffyzxc** [comment]
> Guild Sigils can be downloaded here: https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0f6ff497-8e4a-4009-9ff5-02c45bff0564/

Can we resize them to have the same size (width and height)

**Comment by jeffyzxc** [comment]
Coolio! closing this now

![image](https://user-images.githubusercontent.com/25240940/176412765-cb91294a-b5dd-4e36-9ad3-302deeb9d62e.png)
