### ISSUE TITLE
[Design] - Bazaar My Listings page

### ISSUE THREAD

**Issue by kcper** [CryptoBlades/art-and-design#34]
### **Project**
Bazaar
### **Description**
Design for My Listings page in Bazaar. Current state:
![image](https://user-images.githubusercontent.com/9114200/180725792-9645dc1a-e881-41ab-a8b7-9026cf0473ec.png)
As we start introducing external collections I think we will need an option to pick and only display listings of specific collection. If you have an idea for even better UX that's fine with me.
### **Potential Deadline**
07/27

**Comment by mrlamzz** [comment]
Hi,

I. User will be seeing "Edit / Cancel" on an item in the inventory if it is for sale:

https://xd.adobe.com/view/beba6985-62f6-4705-8473-4f8d0e318b01-ebe9/screen/27b6e2c5-ddad-4a9f-917d-530d4d7745fe/

II. Users can click the profile dropdown to access the My Listings. When the user is on the "My Listings" page, it's the same thing, whatever the selected project on the header dropdown, it will be the one who will show up with its listing:

https://xd.adobe.com/view/beba6985-62f6-4705-8473-4f8d0e318b01-ebe9/screen/6d001aee-c857-42e8-8e93-af324ec8aaf1/
