### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Page typed building 

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#4]
Page typed design for buildings modal

Current design:

**Town hall**
![image](https://user-images.githubusercontent.com/25240940/175920365-31379127-83be-4811-9150-6431f5e12c55.png)

**Headquarters**
![image](https://user-images.githubusercontent.com/25240940/175920451-9521395c-a13f-44e4-90e3-e522cbb27cd8.png)

**Barracks**
![image](https://user-images.githubusercontent.com/25240940/175920506-9ff5e013-081a-4824-bf24-8564c0f5738b.png)

![image](https://user-images.githubusercontent.com/25240940/175920549-d53bd1fd-8c51-4dd5-8dcf-c4b9947ea354.png)

**Stone Mine**
![image](https://user-images.githubusercontent.com/25240940/175920607-75f607ac-067f-49b7-ad19-5b3d30c1d9be.png)

**Claypit**
![image](https://user-images.githubusercontent.com/25240940/175920675-773cce12-6ffc-40fa-8107-d04ff507ffd6.png)

**Forrest Camp**
![image](https://user-images.githubusercontent.com/25240940/175920739-d69bbcf4-18f0-4cfc-b5ee-aa35fa5b9c13.png)

**Church**
![image](https://user-images.githubusercontent.com/25240940/175920824-239ddcb2-0bb5-451c-96d2-308289f8e3e0.png)

**Store House**
![image](https://user-images.githubusercontent.com/25240940/175920864-24df7923-aa54-4cef-9fe1-92ad9e815247.png)

**Smithy**
![image](https://user-images.githubusercontent.com/25240940/175920896-73bf3b0b-a03f-4292-9cf8-965d83448b71.png)

**Rally point**
![image](https://user-images.githubusercontent.com/25240940/175920951-12be8034-5eeb-4bbc-99bb-f9654698ba9f.png)

**Farm**
![image](https://user-images.githubusercontent.com/25240940/175921014-97b83d72-3fdf-4287-8272-5448d7857e45.png)

**Hidden Stash**
![image](https://user-images.githubusercontent.com/25240940/175921081-d1f8fd85-71e0-4132-a412-bf00c808043e.png)

**Wall**
![image](https://user-images.githubusercontent.com/25240940/175921125-9f755411-2a8e-4027-a1c5-f9cabaf4582f.png)

**Trading Post**
![image](https://user-images.githubusercontent.com/25240940/175921175-1c38451b-2e37-4e4c-a21a-668e54c3dd50.png)

**Comment by mrlamzz** [comment]
**Updated Designs:**

**Buildings:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0791f027-d2dc-45d7-bee3-8a4c39329b21/

**View Info:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/7ed7015b-93cd-4fe8-bf58-eaa2a4dc3c9b/

**Pay Silvers:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/d3e2c36a-f12a-4658-90d4-b2cbc4427c6f/

**Comment by jeffyzxc** [comment]
![image](https://user-images.githubusercontent.com/25240940/177497208-d2a51f41-66f7-45d4-8ee6-232b0e28182e.png)

Same with tribal wars users can queue upgrades:

![image](https://user-images.githubusercontent.com/25240940/177497481-c9a596b8-8d2e-41a0-9a15-eb38372f7837.png)

**Comment by mrlamzz** [comment]
**Updated:**

**Buildings:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0791f027-d2dc-45d7-bee3-8a4c39329b21/

**Comment by jeffyzxc** [comment]
Great! thanks zhang!
