### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Guild Invite

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#5]
A place where the recipient of invitation can accept / deny

**Comment by mrlamzz** [comment]
**Join Guild:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/1c01405b-5033-4d04-ba9c-8bb58a6fb2a8/

**View Guild Invitations:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/488221bd-d0e4-4e4c-bce2-385417e1336b/
