### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Missionary

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#6]
Sent how the conquering and colony works in the discord channel

Bit deets on missionary:
- Missionary is trained in the church building
- Missionary is used to conquer villages and barbarian

Requirements:
- Missionary art
- Missionary Icon
- UI design for missionary training
    - A place where users can see the training remaining time
    - Cancel training
    - Missionary cost gold, wood, clay, population

**Comment by mrlamzz** [comment]
**Missionary:**

**Info:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/50c91610-d27a-42f3-8ac9-54dd3bcbca54/

**Training:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/a2f6f488-802c-457f-a427-05355aacfd87/

**Default:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/cfdee16b-ca46-4b1e-884f-881b19c5e175/

**Claiming Village In-Progress:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/e5e23d14-52ee-4420-a781-08d5c226cce9/

**Claim Complete:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/47df8c63-6e7b-4e85-adbb-a28074298ed0/

**Comment by jeffyzxc** [comment]
![image](https://user-images.githubusercontent.com/25240940/177496938-6c24880f-daba-43c3-bffb-74342e581a73.png)

Can we request a hero icon for this as well than you

**Comment by mrlamzz** [comment]
**Updated:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/0f6ff497-8e4a-4009-9ff5-02c45bff0564/
