### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Army movement

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#7]
An interface where they can see all active army movements(Attack, support)

Requirements:
1. Show all active commands
2. Withdraw active commands
3. Arrival time

Current design we have: 
![image](https://user-images.githubusercontent.com/25240940/175928828-da252e06-55ef-4b8e-9b19-d4dd3bbaf16c.png)

**Comment by mrlamzz** [comment]
**Design:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/8995bbdd-f144-4c65-9fdc-8fc6c4a2ae23/
