### ISSUE TITLE
[Art] [Cryptoblades Kingdom] - Colony and conquering

### ISSUE THREAD

**Issue by jeffyzxc** [CryptoBlades/art-and-design#8]
Requirements:

- Inform the user if they have got conquered
   - 25% of their storehouse is no longer them
   - 25% of conquered village income would be stashed and every 3 hours resources from the stash will be sent to master 
   - Market is disabled
- A UI where the conquerors can all villages and colonies they subjugated
   - Ability to switch from your current village to a colony village and vice versa
   - Display the information like: Stash( wood, clay stone), coordinates
- Conquerors can upgrade/build buildings but cannot build churches or train missionaries

**Comment by mrlamzz** [comment]
**Defeat Report:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/a8c1f17a-fd06-4fb8-b865-23dfa77698d2/

**Market Disabled:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/18b70989-c885-4f71-83f0-3c0a9367f9f8/

**All Villages:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/a639dd23-fb49-4a03-af3b-583ba13f66bb/

**Comment by mrlamzz** [comment]
**Updated Description:**

Village Conquering and Colonies

A village can conquer up to 5, 10 or 15 villages based on its tier (T1, T2 and T3 respectively).

**To conquer a village, certain criteria must be met:**

- The conquering village must not be conquered unless it is attacking its conquerer.
- The attack must be succesful and the attacking army must include a Missionary unit.
- The defending village must not be conquered already unless it's a Barbarian village (colony). In such a scenario, it becomes a colony of the latest attacker.
- The conquering village must not have maxed out its quota (5, 10 or 15).

**When a player village is conquered:**

- They lose a portion of their income (25% for example) and a portion of their max storage (25% for example). This will be used to send tributes to their conquerer.
- Every 3 hours, a transport (if available) will be sent to towards the conquering village automatically with a resource type (the one that has max stashed).
- If no transport is available, nothing will be sent and as soon as the "side storage" maxes out, the income returns to normal.
- If the village is liberated, any resource in the "side storage" is credited back.
- A conquered village cannot trade on the market; all transports are confiscated for tribute services.

**Rebelling:**

- A conquered village may rebel once every 7 days. If no attacks are lost within 3 days of the rebellion start, the village is set free.

**Other ways to be set free:**

- Your conquerer being conquered.
- Your conquerer freeing you.

**When a barbarian village is conquered:**

- It becomes a colony; just like any village but has an additional cap on its building levels.
- Owner of conquering village has full control over the colony (can train armies, attack, build etc...)
- Colonies cannot build churches.
- Colonies have levels (1 to 10) decided by the barbarian AI level of the village.
- Building cap in colonies is the regular cap or the colony level whichever is smaller.
- Colonies revert back to barbarians when freed.

**Comment by mrlamzz** [comment]
**Colonization/Conquer UI Designs**

Player can go to the continent map to attack a player or barbarian village:
https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/1895024b-cbd3-4b35-bbb1-96080a605142/

Attack Command: 
https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/3297ff49-028b-488d-8489-f5fc78707aee/

Attack Success Message:
https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/b6a41d35-114e-48cc-9dcd-ebeed151a5bc/

Player can check the status via Rally Point: 
https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/8995bbdd-f144-4c65-9fdc-8fc6c4a2ae23/

Defeated player gets a mail:
https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/a8c1f17a-fd06-4fb8-b865-23dfa77698d2/

Market disabled:
https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/18b70989-c885-4f71-83f0-3c0a9367f9f8/

Player can access his villages to see the conquered/colonized villages:
https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/a639dd23-fb49-4a03-af3b-583ba13f66bb/

Let me know your feedback. Thanks.

**Comment by jeffyzxc** [comment]
Hey can this is siiick!

just a few comments:
1. how can we inform users that their storehouse or max resources decrease by 25%?
2. how can we inform users that that village is conquered?
3. I think we should also add a rebellion button somewhere here
![image](https://user-images.githubusercontent.com/25240940/177498707-2296ac53-6abf-4bb6-a256-08ec2e026259.png)

**Comment by jeffyzxc** [comment]
And how can they navigate to this page? https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/a639dd23-fb49-4a03-af3b-583ba13f66bb/

**Comment by mrlamzz** [comment]
**Updated Village UI:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/96697545-b84d-4344-a70b-3c3f9eaba253/

Also, you can access the villages from the menu. There is a "Villages" menu item there.

**Comment by jeffyzxc** [comment]
> **Updated Village UI:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/96697545-b84d-4344-a70b-3c3f9eaba253/
> 
> Also, you can access the villages from the menu. There is a "Villages" menu item there.

Hey Zhang I couldn't download the units icons

![image](https://user-images.githubusercontent.com/25240940/179933397-003db34b-0254-4262-9573-ab7190dff08e.png)

**Comment by jeffyzxc** [comment]
> **Updated Village UI:** https://xd.adobe.com/view/6302d31a-e489-4756-9ad3-40ffa6deb9b5-3651/screen/96697545-b84d-4344-a70b-3c3f9eaba253/
> 
> Also, you can access the villages from the menu. There is a "Villages" menu item there.

Can we also have a back-to-the-main village on this page?

**Comment by mrlamzz** [comment]
@jeffyzxc  Please refresh same link.
